name: rag-pipeline-gpu
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
  - nvidia

dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Or 12.1 depending on the cluster CUDA version
  - faiss-gpu
  - pip:
      - transformers
      - sentence-transformers
      - pymupdf
      - dspy-ai
      - huggingface_hub
